// Regenerates data/chord-library.json from data/voicing-shapes.json + data/engine-settings.json:
// `npm run generate:chords`. `npm run verify` fails if the checked-in file is out of date.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { PITCH_CLASSES } from "@/lib/musicTheory";
import { SETTINGS, SHAPES, candidates } from "@/lib/voicings";

const ENHARMONIC: Partial<Record<string, string>> = { "C#": "Db", "D#": "Eb", "F#": "Gb", "G#": "Ab", "A#": "Bb" };
const STRINGS = ["e", "B", "G", "D", "A", "E"] as const;

export function chordLibraryJson(): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(
    `  "_generation_note": "GENERATED by scripts/generate-chord-library.ts from data/voicing-shapes.json (fret limit ${SETTINGS.fretLimit} from data/engine-settings.json). Do not edit by hand: run npm run generate:chords. \`chords\` is each root's default two-note voicing (root on whichever of the low E/A/D strings gives the lowest fret), used by the Count In diagram. \`voicings\` lists every playable shape per root, which the voicing engine (lib/voicings.ts) searches.",`,
  );
  lines.push(`  "tuningLowToHigh": ["E2", "A2", "D3", "G3", "B3", "E4"],`);
  lines.push(`  "chords": {`);
  PITCH_CLASSES.forEach((root, pc) => {
    const def = candidates(pc, ["E2", "A2", "D2"]).sort((a, b) => a.notes[0].fret - b.notes[0].fret)[0];
    const [r, f] = def.notes;
    const tab = Object.fromEntries(STRINGS.map((s) => [s, def.notes.find((n) => n.string === s)?.fret.toString() ?? "-"]));
    const enh = ENHARMONIC[root] ? `, "enharmonic": "${ENHARMONIC[root]}"` : "";
    const comma = pc < 11 ? "," : "";
    lines.push(
      `    ${JSON.stringify(root)}: { "rootString": "${r.string}", "rootFret": ${r.fret}, "fifthString": "${f.string}", "fifthFret": ${f.fret}, "twoNoteTab": ${JSON.stringify(tab).replace(/,/g, ", ").replace(/:/g, ": ")}${enh} }${comma}`,
    );
  });
  lines.push("  },");
  lines.push(`  "voicings": {`);
  PITCH_CLASSES.forEach((root, pc) => {
    const all = candidates(pc, SHAPES.map((s) => s.id));
    const list = all.map((v) => `{ "shape": "${v.shapeId}", "notes": "${v.notes.map((n) => `${n.string}${n.fret}`).join(" ")}" }`);
    lines.push(`    ${JSON.stringify(root)}: [`);
    list.forEach((l, i) => lines.push(`      ${l}${i < list.length - 1 ? "," : ""}`));
    lines.push(`    ]${pc < 11 ? "," : ""}`);
  });
  lines.push("  }");
  lines.push("}");
  return lines.join("\n") + "\n";
}

if (process.argv[1]?.endsWith("generate-chord-library.ts")) {
  writeFileSync(join(process.cwd(), "data/chord-library.json"), chordLibraryJson());
  console.log("Wrote data/chord-library.json");
}
